# Changes here will be overwritten by Copier
_commit: '0.6'
_src_path: gh:Netbeheer-Nederland/template-dp
description: Lijst van begrippen gerelateerd aan de data-uitwisseling onder de NBNL
    Profile Group.
exchange_format: JSON-LD
git_protocol: SSH
name: termenlijst
title: Termenlijst
